const technologies = [
    { text: "JavaScript", color: "#F7E018" },
    { text: "TypeScript", color: "#007ACC" },
    { text: "React", color: "#61DAFB" },
    { text: "Next.js", color: "#000000" },
    { text: "Node.js", color: "#8CC84B" },
    { text: "CSS", color: "#1572B6" },
    { text: "HTML", color: "#E34F26" },
    { text: "GitHub", color: "#181717" },
    { text: "Git", color: "#F05032" },
    { text: "Vercel", color: "#000000" },
    { text: "Tailwind", color: "#38B2AC" },
    { text: "AWS", color: "#FF9900" },
    { text: "Docker", color: "#2496ED" },
    { text: "Firebase", color: "#FFCA28" },
    { text: "Redux", color: "#764ABC" },
    { text: "Material UI", color: "#0081CB" },
    { text: "Java", color: "#007396" },
    { text: "Python", color: "#306998" },
    { text: "Spring Boot", color: "#6DB33F" },
    { text: "Go", color: "#00ADD8" },
    { text: "MongoDB", color: "#47A248" },
    { text: "Figma", color: "#F24E1E" },
    { text: "Notion", color: "#000000" },
    { text: "OpenCV", color: "#5C2D91" },
    { text: "C++", color: "#00599C" },
    { text: "C#", color: "#512BD4" },
    { text: "C", color: "#A8B9CC" },
    { text: "OpenGL", color: "#888EB2" },
    { text: "Linux", color: "#FCC624" },
    { text: "WSL", color: "#8CC84B" },
    { text: "Maven", color: "#C71A36" },
  ];
  
  export default technologies;
  